# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='timetracking.Tag'),
        ),
    ]
