# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0004_auto_20160112_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 1, 13, 16, 39, 21, 489928, tzinfo=utc), max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 1, 13, 16, 39, 24, 18523, tzinfo=utc), max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 1, 13, 16, 39, 25, 629069, tzinfo=utc), max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
