# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0006_auto_20160420_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='rocket', max_length=60),
            preserve_default=False,
        ),
    ]
